language: ruby
rvm:
    - 2.6.3

script: scripts/cibuild.sh

deploy:
    local-dir: './_site'
    provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    on:
        branch: master

env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
        sudo: false # route your build to the container-based infrastructure for a faster build
        cache: bundler # caching bundler gem packages will speed up build

