language: ruby
rvm:
    - 2.6.5
cache: bundler

script: scripts/cibuild.sh

deploy:
    local_dir: _site/
    provider: pages
    skip_cleanup: true
    token: "$GITHUB_TOKEN"
    keep_history: true
    on:
        branch: master
