# Site settings
title: Cheuk's Blog
description: > # This means to ignore newlines until "baseurl:"
  Basically, some things that I want to share with others, whether it be stuff I learnt, or some tutorials, updates, or whatever.
baseurl: "" # The subpath of your site, e.g. /blog/
url: "http://cheukyin699.github.io" # The base hostname & protocol for your site

# Usernames
twitter_username: chucksys
github_username:  cheukyin699
email: cheukyin699@yahoo.com

# Pagination
paginate: 10
paginate_path: "/page:num"

# Build settings
markdown: redcarpet
# Syntax highlighter
highlighter: pygments
exclude: [Gemfile]

# Ruby gems
gems:
    - jekyll-sitemap
    - jemoji
    - jekyll-archives


# Jekyll archives gem
jekyll-archives:
    enabled:
        - year
        - month
        - tags
        - categories
    layouts:
        year: archive-year
        month: archive-month
        tag: archive-tag
        category: archive-tag
    permalinks:
        year: '/archives/year/:year/'
        month: '/archives/month/:year-:month/'
        tag: '/archives/tag/:name/'
        category: '/archives/category/:name/'

