# Site settings
title: Cheuk's Blog
tagline: "Student • Programmer • Writer"
baseurl: "" # The subpath of your site, e.g. /blog/
url: "http://cheukyin699.github.io" # The base hostname & protocol for your site

# Usernames
twitter_username: chucksys
github_username:  cheukyin699

# SASS
sass:
    style: compressed

# Build settings
# Syntax highlighter
markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    syntax_highlighter: rouge

# Files to exclude
exclude:
    - Gemfile
    - Gemfile.lock
    - config.ru
    - vendor
    - Procfile
    - Rakefile
    - scripts/

# Ruby gems
plugins:
    - jekyll-coffeescript
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
    - jemoji
